// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp0bYsPPNdqtYE3xVygHQtqx9cCPhHJTs',
    appId: '1:922855108870:web:e46ad316331436e1b32e87',
    messagingSenderId: '922855108870',
    projectId: 'snacktrack-4ac3c',
    authDomain: 'snacktrack-4ac3c.firebaseapp.com',
    storageBucket: 'snacktrack-4ac3c.firebasestorage.app',
    measurementId: 'G-XX8VS0N475',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO87nNY5p3sqPnSuGL-INhD7NsWl7c3Bs',
    appId: '1:922855108870:android:020f3d3ef314c681b32e87',
    messagingSenderId: '922855108870',
    projectId: 'snacktrack-4ac3c',
    storageBucket: 'snacktrack-4ac3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrs-l284HmfRXliYMaOyWPhzE3gtvNb4',
    appId: '1:922855108870:ios:3ed2a04911f8b02fb32e87',
    messagingSenderId: '922855108870',
    projectId: 'snacktrack-4ac3c',
    storageBucket: 'snacktrack-4ac3c.firebasestorage.app',
    iosBundleId: 'com.mohamed.snacktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrs-l284HmfRXliYMaOyWPhzE3gtvNb4',
    appId: '1:922855108870:ios:b1c07872cd09988db32e87',
    messagingSenderId: '922855108870',
    projectId: 'snacktrack-4ac3c',
    storageBucket: 'snacktrack-4ac3c.firebasestorage.app',
    iosBundleId: 'com.example.healthAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp0bYsPPNdqtYE3xVygHQtqx9cCPhHJTs',
    appId: '1:922855108870:web:bb9a0b4abe083136b32e87',
    messagingSenderId: '922855108870',
    projectId: 'snacktrack-4ac3c',
    authDomain: 'snacktrack-4ac3c.firebaseapp.com',
    storageBucket: 'snacktrack-4ac3c.firebasestorage.app',
    measurementId: 'G-FLX2ZC40CX',
  );
}
