import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'services/storage_service.dart';
import 'app.dart';

void main() async {
  // Ensure framework bindings are ready for async initializations
  WidgetsFlutterBinding.ensureInitialized();
  
  // 1. Initialize Local Storage (Perfect setup for your future Hive offline support)
  await StorageService.init();

  // 2. Initialize Firebase Services
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const App());
}